# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

class TestAddnewtoolwithdependency():
  def setup_method(self, method):
    binary = FirefoxBinary(r'C:\Program Files\Mozilla Firefox\firefox.exe')

    self.driver = webdriver.Firefox(executable_path= r'E:\openbioc\OpenBioC\tests\geckodriver.exe', firefox_binary=binary)
    self.driver.maximize_window() #For maximizing window
    self.driver.implicitly_wait(5) #gives an implicit wait for 5 seconds
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addnewtoolwithdependency(self):
    # Test name: add new tool with dependency
    # Step # | name | target | value | comment
    # 1 | open | http://localhost:8200/platform/ |  | 
    self.driver.get("http://localhost:8200/platform/")
    # 2 | setWindowSize | 1552x938 |  | 
    self.driver.set_window_size(1552, 938)
    # 3 | click | id=signInBtn |  | 
    self.driver.find_element(By.ID, "signInBtn").click()
    # 4 | click | css=.ng-pristine > .col > .input-field:nth-child(1) > label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ng-pristine > .col > .input-field:nth-child(1) > label").click()
    # 5 | type | id=signInUsername | gala | 
    self.driver.find_element(By.ID, "signInUsername").send_keys("gala")
    # 6 | click | css=.ng-dirty > .row > .input-field:nth-child(2) > label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ng-dirty > .row > .input-field:nth-child(2) > label").click()
    # 7 | mouseOver | name=action |  | 
    element = self.driver.find_element(By.NAME, "action")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | type | id=signInPassword | galagala | 
    self.driver.find_element(By.ID, "signInPassword").send_keys("galagala")
    # 9 | click | name=action |  | 
    self.driver.find_element(By.NAME, "action").click()
    # 10 | mouseOut | name=action |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    time.sleep(5)
    # 11 | click | css=#toolsDataPlusBtn > .material-icons |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#toolsDataPlusBtn > .material-icons").click()
    # 12 | click | css=.row:nth-child(1) > .m4:nth-child(1) > label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) > .m4:nth-child(1) > label").click()
    # 13 | type | id=generalName | visualize | 
    self.driver.find_element(By.ID, "generalName").send_keys("visualize")
    # 14 | click | css=.row:nth-child(1) > .m4:nth-child(2) > label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) > .m4:nth-child(2) > label").click()
    # 15 | type | id=generalVersion | 1 | 
    self.driver.find_element(By.ID, "generalVersion").send_keys("1")
    # 16 | click | css=.grid-s12-m12-l12:nth-child(4) > label |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid-s12-m12-l12:nth-child(4) > label").click()
    # 17 | type | id=generalDescription | this is a test | 
    self.driver.find_element(By.ID, "generalDescription").send_keys("this is a test")
    # 18 | click | css=#toolsDataDependencies .arrow |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#toolsDataDependencies .arrow").click()
    time.sleep(5)
    # 19 | click | id=leftPanelSearch |  | 
    self.driver.find_element_by_xpath("/html/body/div[1]/div[3]/div[1]/div[2]/div/form/div/div/label").click()    
    #self.driver.find_element(By.ID, "leftPanelSearch").click()
    # 20 | type | id=leftPanelSearch | plink | 
    self.driver.find_element(By.ID, "leftPanelSearch").send_keys("plink")
    # 21 | click | css=#toolsData .arrow |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#toolsData .arrow").click()
    # 22 | mouseDownAt | id=tools_dep_jstree_id | 145,62 | 
    element = self.driver.find_element(By.ID, "tools_dep_jstree_id")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 23 | mouseMoveAt | id=tools_dep_jstree_id | 145,62 | 
    element = self.driver.find_element(By.ID, "tools_dep_jstree_id")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 24 | mouseUpAt | id=tools_dep_jstree_id | 145,62 | 
    element = self.driver.find_element(By.ID, "tools_dep_jstree_id")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 25 | click | css=.splitter-container |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".splitter-container").click()
    # 26 | click | css=#toolsDataInstallation > .collapsible-header |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#toolsDataInstallation > .collapsible-header").click()
    # 27 | click | css=.select-dropdown:nth-child(1) |  | 
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".select-dropdown:nth-child(1)").click()
    # 28 | click | css=#select-options-6bb92280-8de4-c88a-1485-25c65dfb311d2 > span span |  | 
    #self.driver.find_element(By.CSS_SELECTOR, "#select-options-6bb92280-8de4-c88a-1485-25c65dfb311d2 > span span").click()
    
	# 29 | removeSelection | id=tool_os_choices_select | label=POSIX system | 
    #dropdown = self.driver.find_element(By.ID, "tool_os_choices_select")
    #dropdown.find_element(By.XPATH, "//option[. = 'POSIX system']").click()
    # 30 | removeSelection | id=tool_os_choices_select | label=Ubuntu:14.04 | 
    #dropdown = self.driver.find_element(By.ID, "tool_os_choices_select")
    #dropdown.find_element(By.XPATH, "//option[. = 'Ubuntu:14.04']").click()
    # 31 | addSelection | id=tool_os_choices_select | label=Ubuntu:16.04 | 
    dropdown = self.driver.find_element(By.ID, "tool_os_choices_select")
    #dropdown.find_element(By.XPATH, "//option[. = 'Ubuntu:16.04']").click()
    # 32 | removeSelection | id=tool_os_choices_select | label=Debian 8 (Jessie) | 
    #dropdown = self.driver.find_element(By.ID, "tool_os_choices_select")
    #dropdown.find_element(By.XPATH, "//option[. = 'Debian 8 (Jessie)']").click()
    # 33 | removeSelection | id=tool_os_choices_select | label=Debian 9 (Stretch) | 
    #dropdown = self.driver.find_element(By.ID, "tool_os_choices_select")
    #dropdown.find_element(By.XPATH, "//option[. = 'Debian 9 (Stretch)']").click()
    # 34 | removeSelection | id=tool_os_choices_select | label=Debian 10 (Buster) | 
    #dropdown = self.driver.find_element(By.ID, "tool_os_choices_select")
    #dropdown.find_element(By.XPATH, "//option[. = 'Debian 10 (Buster)']").click()
	
	
    # 35 | click | css=#toolsDataInstallation > .collapsible-body |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#toolsDataInstallation > .collapsible-body").click()
    # 36 | click | css=#tool_installation_editor .ace_content |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#tool_installation_editor .ace_content").click()
    # 37 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 38 | type | css=#tool_installation_editor > .ace_text-input | exit 0\n\n | 
    self.driver.find_element(By.CSS_SELECTOR, "#tool_installation_editor > .ace_text-input").send_keys("exit 0\\n\\n")
    # 39 | click | css=#tool_validation_editor .ace_content |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#tool_validation_editor .ace_content").click()
    # 40 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 41 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 42 | type | css=#tool_validation_editor > .ace_text-input | exit 0\n\n | 
    self.driver.find_element(By.CSS_SELECTOR, "#tool_validation_editor > .ace_text-input").send_keys("exit 0\\n\\n")
    # 43 | click | css=.row:nth-child(5) > .waves-effect:nth-child(1) > .material-icons |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(5) > .waves-effect:nth-child(1) > .material-icons").click()
  
