apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  obc_private.py: |
    from .settings import *

    SECRET_KEY = {{ default (randAlphaNum 50) .Values.openbio.djangoSecret | quote }}
    DEBUG = {{- if .Values.openbio.djangoDebug }} True {{- else }} False {{- end }}

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'openbio',
            'USER': 'openbio',
            'HOST': '127.0.0.1',
            'PORT': 5432
         }
    }

    TITLE = {{ .Values.openbio.title | quote }}
    SERVER = {{ .Values.openbio.serverURL | quote }}
    EMAIL = {{ .Values.openbio.fromEmail | quote }}
    ADMIN = {{ .Values.openbio.adminEmail | quote }}
    TERMS = {{ .Values.openbio.termsURL | quote }}
    PRIVACY = {{ .Values.openbio.privacyURL | quote }}
    FUNDING_LOGOS = {{- if .Values.openbio.showFundingLogos }} True {{- else }} False {{- end }}

    {{- if and .Values.openbio.ingressEnabled (eq (.Values.openbio.serverURL | urlParse).scheme "https") }}
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_SCHEME', 'https')
    {{- end }}

    {{- if .Values.openbio.knotEndpointURL }}
    from social_core.backends.open_id_connect import OpenIdConnectAuth

    class KnotConnect(OpenIdConnectAuth):
        name = 'knot'
        OIDC_ENDPOINT = {{ .Values.openbio.knotEndpointURL | quote }}
        EXTRA_DATA = OpenIdConnectAuth.EXTRA_DATA + ['knot_namespace', 'knot_ingress_url', 'knot_private_registry_url', 'knot_argo_workflows_url']

    AUTHENTICATION_BACKENDS = ('OpenBio.obc_private.KnotConnect',) + AUTHENTICATION_BACKENDS

    SOCIAL_AUTH_POSTGRES_JSONFIELD = True
    {{- if not .Values.openbio.knotVerifySSL }}
    SOCIAL_AUTH_VERIFY_SSL = False
    {{- end }}
    SOCIAL_AUTH_KNOT_KEY = {{ required "You must set openbio.knotClientID" .Values.openbio.knotClientID | quote }}
    SOCIAL_AUTH_KNOT_SECRET = {{ required "You must set openbio.knotClientSecret" .Values.openbio.knotClientSecret | quote }}

    LOGIN_BACKEND = KnotConnect.name
    {{- end }}

    {{- if .Values.openbio.extraSettings }}
    {{- .Values.openbio.extraSettings | nindent 4 }}
    {{- end }}
