# Generated by Django 2.2.20 on 2021-07-28 08:33

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_html', models.TextField()),
                ('title', models.CharField(max_length=1000)),
                ('opinion', models.CharField(choices=[(1, 'note'), (2, 'agree'), (3, 'disagree'), (4, 'solution'), (5, 'issue')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('children', models.ManyToManyField(related_name='comment_children', to='app.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('client', models.URLField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OBC_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_validated', models.BooleanField()),
                ('email_validation_token', models.CharField(max_length=32, null=True)),
                ('password_reset_token', models.CharField(max_length=32, null=True)),
                ('password_reset_timestamp', models.DateTimeField(null=True)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256, null=True)),
                ('website', models.URLField(max_length=256, null=True)),
                ('affiliation', models.TextField(null=True)),
                ('public_info', models.TextField(null=True)),
                ('clients', models.ManyToManyField(to='app.ExecutionClient')),
            ],
        ),
        migrations.CreateModel(
            name='OS_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_choices', models.CharField(choices=[('posix', 'POSIX system'), ('ubuntu:14.04', 'Ubuntu:14.04'), ('ubuntu:16.04', 'Ubuntu:16.04'), ('debian:8', 'Debian 8 (Jessie)'), ('debian:9', 'Debian 9 (Stretch)'), ('debian:10', 'Debian 10 (Buster)'), ('osx:1', 'Mac OSX Intel')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ReportToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('version', models.CharField(max_length=256)),
                ('edit', models.IntegerField()),
                ('website', models.URLField(max_length=256, null=True)),
                ('description', models.TextField(null=True)),
                ('description_html', models.TextField(null=True)),
                ('changes', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation_commands', models.TextField()),
                ('validation_commands', models.TextField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('draft', models.BooleanField()),
                ('visibility', models.CharField(choices=[(1, 'public'), (2, 'private')], default=1, max_length=100)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_comment', to='app.Comment')),
                ('dependencies', models.ManyToManyField(related_name='dependencies_related', to='app.Tool')),
                ('forked_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forked_from_related', to='app.Tool')),
                ('keywords', models.ManyToManyField(to='app.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('edit', models.IntegerField()),
                ('website', models.URLField(max_length=256, null=True)),
                ('description', models.TextField()),
                ('description_html', models.TextField()),
                ('workflow', models.TextField()),
                ('changes', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('draft', models.BooleanField()),
                ('visibility', models.CharField(choices=[(1, 'public'), (2, 'private')], default=1, max_length=100)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_comment', to='app.Comment')),
                ('forked_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forked_from_related', to='app.Workflow')),
                ('keywords', models.ManyToManyField(to='app.Keyword')),
                ('obc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user')),
                ('tools', models.ManyToManyField(related_name='workflows_using_me', to='app.Tool')),
                ('workflows', models.ManyToManyField(related_name='workflows_using_me', to='app.Workflow')),
            ],
            options={
                'unique_together': {('name', 'edit')},
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_related', to='app.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='UpDownWorkflowVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='UpDownToolVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tool')),
            ],
        ),
        migrations.CreateModel(
            name='UpDownCommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Comment')),
                ('obc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user')),
            ],
        ),
        migrations.CreateModel(
            name='ToolValidations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=256)),
                ('validation_status', models.CharField(max_length=256)),
                ('errcode', models.IntegerField(null=True)),
                ('stdout', models.TextField(null=True)),
                ('stderr', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='last_validation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_validation_related', to='app.ToolValidations'),
        ),
        migrations.AddField(
            model_name='tool',
            name='obc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user'),
        ),
        migrations.AddField(
            model_name='tool',
            name='os_choices',
            field=models.ManyToManyField(to='app.OS_types'),
        ),
        migrations.AddField(
            model_name='tool',
            name='variables',
            field=models.ManyToManyField(related_name='tools_related', to='app.Variables'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nice_id', models.CharField(default=app.models.create_nice_id, editable=False, max_length=10, unique=True)),
                ('url', models.URLField(max_length=256, null=True)),
                ('log_url', models.URLField(max_length=256, null=True)),
                ('visualization_url', models.URLField(max_length=256, null=True)),
                ('monitor_url', models.URLField(max_length=256, null=True)),
                ('client_status', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ExecutionClient')),
                ('obc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user')),
                ('tokens', models.ManyToManyField(related_name='report_related', to='app.ReportToken')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=256)),
                ('doi', models.URLField(max_length=256, null=True)),
                ('bibtex', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fields', models.ManyToManyField(related_name='reference_related', to='app.ReferenceField')),
                ('obc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user')),
            ],
        ),
        migrations.AddField(
            model_name='obc_user',
            name='references',
            field=models.ManyToManyField(related_name='users_authored_me', to='app.Reference'),
        ),
        migrations.AddField(
            model_name='obc_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='obc_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OBC_user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent', to='app.Comment'),
        ),
        migrations.AddIndex(
            model_name='updownworkflowvote',
            index=models.Index(fields=['obc_user', 'workflow'], name='UpDownWorkflowVote_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='updownworkflowvote',
            unique_together={('obc_user', 'workflow')},
        ),
        migrations.AddIndex(
            model_name='updowntoolvote',
            index=models.Index(fields=['obc_user', 'tool'], name='UpDownToolVote_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='updowntoolvote',
            unique_together={('obc_user', 'tool')},
        ),
        migrations.AddIndex(
            model_name='updowncommentvote',
            index=models.Index(fields=['obc_user', 'comment'], name='UpDownCommentVote_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='updowncommentvote',
            unique_together={('obc_user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('name', 'version', 'edit')},
        ),
    ]
