# Generated by Django 2.2.20 on 2022-01-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionclient',
            name='client',
        ),
        migrations.AddField(
            model_name='executionclient',
            name='parameters',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='refresh_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
