"""
Django settings for OpenBioC project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys


try:
    from .obc_private import external_app_dirs
    for directory in external_app_dirs:
        # https://stackoverflow.com/questions/3948356/how-to-keep-all-my-django-applications-in-specific-folder
        # directories to other apps
        sys.path.insert(0, directory)
except ImportError:
    pass

try:
    from .obc_private import INSTALLED_APPS_EXTRA
except ImportError:
    INSTALLED_APPS_EXTRA = []

try:
	from .obc_private import ALLOWED_HOSTS
except ImportError:
	ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1','139.91.81.103','139.91.190.239','192.168.1.13']

try:
	from .obc_private import SECRET_KEY
except ImportError:
	SECRET_KEY = '!!!!!!!!!!!!!!!thisisnotasecretkey!!!!!!!!!!!!!!!!'

if 'thisisnotasecretkey' in SECRET_KEY:
	print ('WARNING: SECRET KEY IS NOT SET!!')

try:
	from .obc_private import POSTGRESQL_PARAMS
except ImportError:
	POSTGRESQL_PARAMS = None

try:
	from .obc_private import DEBUG
except ImportError:
	DEBUG = True

try:
	from .obc_private import STATIC_ROOT
except ImportError:
	pass

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'm0tm#+tfuz280_^5yi(thruaz0hts$f(=knb!pk3m7%@8nh776'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

#ALLOWED_HOSTS = ['0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'app',
] + INSTALLED_APPS_EXTRA

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OpenBioC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OpenBioC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

SQLITE3_PARAMS = {
	'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
}

DATABASES = {
    'default': POSTGRESQL_PARAMS if POSTGRESQL_PARAMS else SQLITE3_PARAMS
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_CONTENT_NEGOTIATION_CLASS': 'app.negotiation.IgnoreClientContentNegotiation',
}


